name: run main.py

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # - name: install python packages
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: execute py script
        env:
          CHAT_TOKEN: ${{ secrets.CHAT_TOKEN }}
        run: python main.py